alias gs='git status'
alias bat='bat -p'
alias b='bat -p'
alias gb='git branch --remote'
alias ll='eza -l --no-time --no-permissions --no-user --git --no-filesize --all --sort type'
alias l='eza -G --no-time --no-permissions --no-user --no-filesize --sort type'
alias la='eza -G --no-time --no-permissions --no-user --no-filesize --all --sort type'
